### PR TITLE
fix(embedded/remotestorage/s3): S3 compatibility fixes

### LINKED ISSUE #1207: Unable to load default database: unable to open transaction log: strconv.ParseInt
**What happened**
An error on start database with S3 Storage when container is starting
Error: unable to open transaction log: strconv.ParseInt: parsing "immudb-backup%2Fdefaultdb%2Ftx%2F00000000": invalid syntax

**What you expected to happen**
App should start correct

**How to reproduce it (as minimally and precisely as possible)**
Create docker container (in my option pod in K8s) with S3 credential and restart it

**Environment**
Kubernetes (helm chart)

### PR DESCRIPTION
**Pull request by byo**
In some setups (elest.io minio containers) HEAD requets fail
when talking to the container. Workaround the HEAD request
by using object lists instead.

Also correctly handle URL-encoded object names and paths when
getting the list, fixes #1207.

Signed-off-by: Bartłomiej Święcki <bart@codenotary.com>

### CODE REVIEW

File: embedded/remotestorage/s3/s3.go [hunk 1]
```diff
@@ -481,38 +482,37 @@ func (s *Storage) Put(ctx context.Context, name string, fileName string) error {
 // Note that due to an asynchronous nature of cloud storage,
 // a resource stored with the Put method may not be immediately accessible.
 func (s *Storage) Exists(ctx context.Context, name string) (bool, error) {
-	if strings.HasPrefix(name, "/") || strings.HasSuffix(name, "/") {
+	if strings.Contains(name, "//") {
```
Comment (jeroiraz) [inline embedded/remotestorage/s3/s3.go:485]: validation could be at `listEntries`

File: embedded/remotestorage/s3/s3.go [hunk 2]
```diff
@@ -481,38 +482,37 @@ func (s *Storage) Put(ctx context.Context, name string, fileName string) error {
...
 	}
-	resp.Body.Close()
 
-	return resp.StatusCode == 200, nil
+	return false, nil
 }
 
 func (s *Storage) ListEntries(ctx context.Context, path string) ([]remotestorage.EntryInfo, []string, error) {
-
 	if path != "" {
```
Comment (jeroiraz) [inline embedded/remotestorage/s3/s3.go:505]: validation could be at `listEntries` ?

File: embedded/remotestorage/s3/s3.go [hunk 3]
```diff
@@ -481,38 +482,37 @@ func (s *Storage) Put(ctx context.Context, name string, fileName string) error {
...
-		[]int{200, 404},
-		func() (io.Reader, string, error) { return nil, "", nil },
-		func(req *http.Request) error { return nil },
-	)
-	if err != nil {
-		return false, err
+	// We're looking for all entries with the prefix, since those
+	// are sorted alphabetically, if there's an entry with exact
+	// name, it would be the first one returned.
+	if len(entries) > 0 && entries[0].Name == "" {
```
Comment (jeroiraz) [inline embedded/remotestorage/s3/s3.go:497]: not sure I understand when `entries[0].Name == ""` holds

File: embedded/remotestorage/s3/s3.go (hunk 2 above)
Comment (byo) [reply embedded/remotestorage/s3/s3.go]: Updated the code a bit, now it's more clear.

File: embedded/remotestorage/s3/s3.go (hunk 1 above)
Comment (byo) [reply embedded/remotestorage/s3/s3.go]: Updated the code.

File: embedded/remotestorage/s3/s3.go [hunk 4]
```diff
@@ -71,7 +88,12 @@ func Open(
...
-		return nil, ErrInvalidArguments
+		return nil, ErrInvalidArgumentsBucketSlash
+	}
+
+	// Bucket name must not be empty
+	if bucket == "" {
+		return nil, ErrInvalidArgumentsBucketEmpty
 	}
 
 	// if prefix is not empty, it must end with '/'
```
Comment (jeroiraz) [inline embedded/remotestorage/s3/s3.go:99]: is it safe for prefixes to contain slashes?

File: embedded/remotestorage/s3/s3.go [hunk 5]
```diff
@@ -481,39 +512,42 @@ func (s *Storage) Put(ctx context.Context, name string, fileName string) error {
 // Note that due to an asynchronous nature of cloud storage,
 // a resource stored with the Put method may not be immediately accessible.
 func (s *Storage) Exists(ctx context.Context, name string) (bool, error) {
-	if strings.HasPrefix(name, "/") || strings.HasSuffix(name, "/") {
-		return false, ErrInvalidArguments
-	}
-
-	url, err := s.originalRequestURL(name)
+	entries, _, err := s.scanObjectNames(ctx, name, 1)
```
Comment (jeroiraz) [inline embedded/remotestorage/s3/s3.go:515]: wondering why `Exists` doesn't accept names or prefixes with slashes but `Get` method accept it

File: embedded/remotestorage/s3/s3.go (hunk 4 above)
Comment (byo) [reply embedded/remotestorage/s3/s3.go:99]: yes, like if you want to scan sub-folders, e.g. `defaultdb/index/`
